name: Code Quality - Static Code - Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt -y install cppcheck
    - name: Install avr-gcc
      run: sudo apt-get install gcc-avr
    - name: Run cppcheck
      run: cppcheck Implementation_Codefiles
